"""Event schemas and asynchronous in-memory event bus for AURA components."""

import asyncio
from datetime import datetime, timezone
from typing import Any, Callable, Coroutine, Dict, List, Optional
from pydantic import BaseModel, Field

from aura_core.enums import AgentState, ReasonCodes


class BaseEvent(BaseModel):
    """Base event contract."""
    event_id: str
    event_type: str
    timestamp: float = Field(default_factory=lambda: datetime.now(timezone.utc).timestamp())
    payload: Dict[str, Any] = Field(default_factory=dict)


class TelemetryEvent(BaseEvent):
    """Robot physical telemetry broadcast."""
    event_type: str = "TELEMETRY"
    robot_id: str
    location: List[float]
    battery: float
    status: str


class AgentStateChangeEvent(BaseEvent):
    """Agent lifecycle state change broadcast."""
    event_type: str = "AGENT_STATE_CHANGE"
    previous_state: AgentState
    new_state: AgentState
    reason_code: Optional[ReasonCodes] = None


class ObstacleDetectedEvent(BaseEvent):
    """Sensory obstacle detection event."""
    event_type: str = "OBSTACLE_DETECTED"
    location: List[float]
    corridor_id: str
    is_dynamic: bool = True


class ReplanTriggerEvent(BaseEvent):
    """Replan trigger event generated by failure detection."""
    event_type: str = "REPLAN_TRIGGER"
    trigger: str
    affected_task_id: str
    reason_codes: List[ReasonCodes]


class SafetyViolationEvent(BaseEvent):
    """Deterministic safety rejection event."""
    event_type: str = "SAFETY_VIOLATION"
    attempted_action: str
    violating_parameters: Dict[str, Any]
    reason: str


class EventBus:
    """Lightweight in-memory asynchronous pub/sub event bus."""

    def __init__(self) -> None:
        self._subscribers: Dict[str, List[Callable[[BaseEvent], Coroutine[Any, Any, None]]]] = {}

    def subscribe(self, event_type: str, callback: Callable[[BaseEvent], Coroutine[Any, Any, None]]) -> None:
        if event_type not in self._subscribers:
            self._subscribers[event_type] = []
        self._subscribers[event_type].append(callback)

    async def publish(self, event: BaseEvent) -> None:
        # Direct topic subscribers
        handlers = self._subscribers.get(event.event_type, [])[:]
        # Wildcard subscribers
        handlers.extend(self._subscribers.get("*", []))
        
        for handler in handlers:
            try:
                await handler(event)
            except Exception as exc:
                print(f"[EventBus] Error in handler {handler.__name__}: {exc}")


# Global event bus singleton
global_event_bus = EventBus()
